parameters:
- name: directory
  type: string

steps:
- task: Npm@1
  displayName: Install ${{ replace(parameters.directory, '/', '_') }}
  inputs:
    command: install
    workingDir: ${{ parameters.directory }}

- script: zip -r "${stagingDir}/${lambdaName}.zip" .
  displayName: Zip ${{ replace(parameters.directory, '/', '_') }}
  workingDirectory: ${{ parameters.directory }}
  env:
    lambdaName: ${{ replace(parameters.directory, '/', '_') }} 
    stagingDir: $(Build.ArtifactStagingDirectory)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: ${{ replace(parameters.directory, '/', '_') }}
  displayName: Publish ${{ replace(parameters.directory, '/', '_') }}