parameters:
- name: directory
  type: string
- name: artifactName
  type: string

steps:
- task: Npm@1
  displayName: Install ${{ parameters.artifactName }}
  inputs:
    command: install
    workingDir: ${{ parameters.directory }}

- script: zip -r "${stagingDir}/${artifactName}.zip" .
  displayName: Zip ${{ parameters.artifactName }}
  workingDirectory: ${{ parameters.directory }}
  env:
    artifactName: ${{ parameters.artifactName }} 
    stagingDir: $(Build.ArtifactStagingDirectory)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: ${{ parameters.artifactName }}
  displayName: Publish ${{ parameters.artifactName }}