parameters:
- name: job
  type: string
- name: displayName
  type: string
  default: ''
- name: dependsOn
  type: object
  default: ''
- name: condition
  type: string
  default: ''
- name: steps
  type: stepList
- name: variables
  type: object
  default: ''

jobs:
- job: ${{ parameters.job }}
  ${{ if ne(parameters.displayName, '') }}:
    displayName: ${{ parameters.displayName }}

  ${{ if ne(parameters.dependsOn, '') }}:
    dependsOn: ${{ parameters.dependsOn }}

  ${{ if ne(parameters.condition, '') }}:
    condition: ${{ parameters.condition }}

  variables:
    CONTAINER_IMAGE: $[ coalesce(dependencies.GetContainerImage.outputs['GetImage.url'], stageDependencies.Validate.GetContainerImage.outputs['GetImage.url'], '') ]
    ${{ if ne(parameters.variables, '') }}:
      ${{ each var in parameters.variables }}:
        ${{ var.Key }}: ${{ var.Value }}
  container: 
    image: $(CONTAINER_IMAGE)
    env:
      CI: true
  steps:
  - script: printenv
  - ${{ parameters.steps }}