parameters:
- name: job
  type: string
- name: displayName
  type: string
  default: ''
- name: dependsOn
  type: object
  default: ''
- name: condition
  type: string
  default: ''
- name: steps
  type: stepList

jobs:
- job: Debug
  dependsOn: GetContainerImage
  condition: ${{ parameters.condition }}
  variables:
    taskDepends: $[ dependencies.GetContainerImage.outputs['GetImage.url'] ]
    stageDepends: $[ stageDependencies.Validate.GetContainerImage.outputs['GetImage.url'] ]
    CONTAINER_IMAGE: $[ coalesce(dependencies.GetContainerImage.outputs['GetImage.url'], stageDependencies.Validate.GetContainerImage.outputs['GetImage.url'], '') ]
  steps:
  - script: echo $(taskDepends)
  - script: echo $(stageDepends)
  - script: echo $(CONTAINER_IMAGE)

- job: ${{ parameters.job }}
  ${{ if ne(parameters.displayName, '') }}:
    displayName: ${{ parameters.displayName }}

  ${{ if ne(parameters.dependsOn, '') }}:
    dependsOn: ${{ parameters.dependsOn }}

  ${{ if ne(parameters.condition, '') }}:
    condition: ${{ parameters.condition }}

  variables:
    CONTAINER_IMAGE: coalesce($[dependencies.GetContainerImage.outputs['GetImage.url']], $[stageDependencies.Validate.GetContainerImage.outputs['GetImage.url']], '')
  container: 
    image: $(CONTAINER_IMAGE)
    env:
      CI: true
  steps:
  - ${{ parameters.steps }}