variables:
- ${{ if and(ne(variables.Build.SourceBranchName, 'master'), ne(variables.Build.Reason, 'PullRequest')) }}:
  - group: 'DEV'

- ${{ if and(ne(variables.Build.SourceBranchName, 'master'), eq(variables.Build.Reason, 'PullRequest')) }}:
  - group: 'QA'

- ${{ if eq(variables.Build.SourceBranchName, 'master') }}:
  - group: 'UAT'