parameters:
- name: chooseEnvironment
  type: string
  default: ''
- name: defaultBranchName
  type: string
  default: master
- name: skipDEV
  type: boolean
  default: false
- name: skipUAT
  type: boolean
  default: false

variables:
- ${{ if or(eq(parameters.chooseEnvironment, 'DEV'), and(eq(parameters.skipDEV, false), ne(variables['Build.SourceBranchName'], parameters.defaultBranchName), ne(variables['Build.Reason'], 'PullRequest'))) }}:
  - group: 'DEV'

- ${{ if or(eq(parameters.chooseEnvironment, 'QA'), and(ne(variables['Build.SourceBranchName'], parameters.defaultBranchName), or(eq(variables['Build.Reason'], 'PullRequest'), eq(parameters.skipDEV, true)))) }}:
  - group: 'QA'

- ${{ if or(eq(parameters.chooseEnvironment, 'UAT'), and(eq(parameters.skipUAT, false), eq(variables['Build.SourceBranchName'], parameters.defaultBranchName), ne(variables['Build.Reason'], 'Manual'))) }}:
  - group: 'UAT'

- ${{ if or(eq(parameters.chooseEnvironment, 'PRD'), and(eq(variables['Build.SourceBranchName'], parameters.defaultBranchName), or(eq(variables['Build.Reason'], 'Manual'), eq(parameters.skipUAT, true)))) }}:
  - group: 'PRD'