parameters:
- name: defaultBranchName
  type: string
  default: 'master'

variables:
- ${{ if and(ne(variables['Build.Build.SourceBranchName'], 'master'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - group: 'DEV'

- ${{ if and(ne(variables['Build.Build.SourceBranchName'], 'master'), eq(variables['Build.Reason'], 'PullRequest')) }}:
  - group: 'QA'

- ${{ if eq(variables['Build.Build.SourceBranchName'], 'master') }}:
  - group: 'UAT'