parameters:
- name: defaultBranchName
  type: string
  default: 'master'
# determine what set of templates will be used for the pipeline
- name: deployType 
  type: string
  default: 'null'
  values:
  - 'null'
  - ADO
  - ReactApp
  - LambdaService
# use a Docker container to run Validate and Build stages
# expects a named image, otherwise uses your repo's devcontainer (default)
- name: useContainerImage 
  type: string
  default: true
# execute Terraform from the repo's '/terraform' directory
# pass a valid terraform version number to force use of that version
- name: useTerraform
  type: string
  default: true

variables:
- template: helpers/select-environment.yml
  parameters:
    defaultBranchName: ${{ parameters.defaultBranchName }}

- ${{ if or(ne(parameters.useTerraform, false), eq(parameters.deployType, 'ADO')) }}:
  - template: Terraform/environment.yml
    parameters:
      AWS_ACCOUNT: $(AWS_ACCOUNT)  
      AWS_REGION: $(AWS_REGION)
      ENVIRONMENT_NAME: $(ENVIRONMENT_NAME)
      repoName: $(Build.Repository.Name)
      sourcesDirectory: $(Build.SourcesDirectory)

stages:
# Find the docker image for later stages
- ${{ if and(ne(parameters.deployType, 'null'), ne(parameters.useContainerImage, false)) }}:
  - stage: Initialise
    jobs: 
    - job: GetContainerImage
      displayName: Get Container Image
      steps:
      - template: helpers/container-get-image.yml
        parameters:
          useContainerImage: ${{ parameters.useContainerImage }}

- stage: Validate
  jobs:
  - ${{ if ne(parameters.useTerraform, false) }}:
    - template: Terraform/validate.yml
      parameters:
        useTerraform: ${{ parameters.useTerraform }}

  - ${{ if ne(parameters.deployType, 'null') }}:  
    - template: helpers/container-job.yml
      parameters: 
        job: ValidateSources
        displayName: Validate Source Code
        condition: or(eq(variables.ENVIRONMENT_NAME, 'DEV'), eq(variables.ENVIRONMENT_NAME, 'QA'))
        steps:
        - template: ${{ parameters.deployType }}/validate.yml

- ${{ if ne(parameters.deployType, 'null') }}:
  - stage: Build
    ${{ if in(parameters.deployType, 'LambdaService') }}:
      # Build once, deploy anywhere
      condition: or(eq(variables.ENVIRONMENT_NAME, 'DEV'), eq(variables.ENVIRONMENT_NAME, 'QA'))
    dependsOn:
    - Validate
    - ${{ if and(ne(parameters.deployType, 'null'), ne(parameters.useContainerImage, false)) }}: 
      - Initialise
    - ${{ if in(parameters.deployType, 'ReactApp') }}:
      # Build for each environment, depending on infrastructure
      - Deploy
    jobs:
    - template: helpers/container-job.yml
      parameters: 
        job: BuildSources
        displayName: Build ${{ parameters.deployType }}
        steps:
        - template: ${{ parameters.deployType }}/build.yml

- stage: Deploy
  dependsOn:
  - Validate
  - ${{ if and(ne(parameters.deployType, 'null'), ne(parameters.useContainerImage, false)) }}: 
    - Initialise
  - ${{ if in(parameters.deployType, 'LambdaService') }}:
    - Build
  jobs:
  - ${{ if ne(parameters.useTerraform, false) }}:
    - template: Terraform/deploy.yml
      parameters:
        useTerraform: ${{ parameters.useTerraform }}
        ${{ if in(parameters.deployType, 'LambdaService') }}:
          preDeploySteps: 
          - template: ${{ parameters.deployType }}/deploy.yml
  - ${{ if eq(parameters.deployType, 'ADO') }}:
    - template: ADO/deploy.yml
      parameters:
        useTerraform: ${{ parameters.useTerraform }}

- ${{ if in(parameters.deployType, 'ReactApp') }}:
  # Provision each environment, depending on infrastructure
  - stage: Provision
    dependsOn: 
      - Deploy
      - Build
    jobs:
    - deployment: ProvisionResources
      displayName: Provision ${{ parameters.deployType }}
      environment: $(ENVIRONMENT_NAME)
      strategy:
        runOnce:
          deploy:  
            steps:
            - template: ${{ parameters.deployType }}/deploy.yml                  