parameters:
- name: deployType 
  type: string
  default: 'null'
- name: preDeploySteps
  type: stepList
  default: []
- name: useTerraform
  type: string
  default: true

jobs:
- deployment: Terraform
  dependsOn: Validate
  variables:
    IS_REQUIRED: $[ stageDependencies.Validate.TerraformPlan.outputs['TerraformCondition.isRequired'] ]
  condition: ne(variables.IS_REQUIRED, 'false')
  environment: $(ENVIRONMENT_NAME)
  strategy:
    runOnce:
      deploy:  
        steps:
        - checkout: self

        - ${{ parameters.preDeploySteps }}
              
        - download: current
          artifact: tfplan-$(ENVIRONMENT_NAME)
          displayName: Get tfplan

        - template: init.yml
          parameters:
            useTerraform: ${{ parameters.useTerraform }}

        - task: TerraformTaskV1@0
          displayName: Apply Terraform
          name: TerraformApply
          ${{ if eq(parameters.deployType, 'ADO') }}:
            env:
              AZDO_PERSONAL_ACCESS_TOKEN: '$(AZDO_PERSONAL_ACCESS_TOKEN)'
          inputs:
            provider: $(TF_PROVIDER)
            command: apply
            workingDirectory: $(TF_PATH)
            commandOptions: $(Pipeline.Workspace)/tfplan-$(ENVIRONMENT_NAME)/tfplan
            environmentServiceNameAWS: $(TF_SERVICE_CONNECTOR)

        - script: mv $(TerraformApply.jsonOutputVariablesPath) $(Build.StagingDirectory)/tfoutput.json
          name: GetTFOutputFileName
          displayName: Get Terraform Output

        - publish: $(Build.StagingDirectory)
          artifact: tfoutput-$(ENVIRONMENT_NAME)
          displayName: Publish Terraform Output