# Used to inject terraform environment variables into the pipeline
parameters:
- name: AWS_ACCOUNT 
  type: string
- name: AWS_REGION
  type: string
- name: ENVIRONMENT_NAME
  type: string
- name: repoName
  type: string
- name: sourcesDirectory
  type: string
- name: terraformProvider
  type: string
  default: 'aws'
  values: 
  - 'aws'
  - 'azurerm'
- name: terraformVersion
  type: string
  default: ''

variables:
  TF_PROVIDER: ${{ parameters.terraformProvider }}
  TF_VERSION: ${{ parameters.terraformVersion }}
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_BACKEND_BUCKET: ${{ parameters.AWS_ACCOUNT }}-state
  TF_BACKEND_KEY: ${{ parameters.repoName }}-iam.tfstate
  TF_PATH: ${{ parameters.sourcesDirectory }}/terraform
  TF_VAR_AWS_ACCOUNT: ${{ parameters.AWS_ACCOUNT }}
  TF_VAR_AWS_REGION: ${{ parameters.AWS_REGION }}
  TF_VAR_AWS_ROLE_ARN: arn:aws:iam::${{ parameters.AWS_ACCOUNT }}:role/$(CICD_ROLE_NAME)
  TF_VAR_ENVIRONMENT: ${{ parameters.ENVIRONMENT_NAME }}
  TF_VAR_PROJECT: ${{ variables['System.TeamProject'] }}
  TF_VAR_UPDATED_BY: ${{ variables['Build.RequestedForEmail'] }}
  TF_VAR_FILE: ./tfvars/${{ parameters.ENVIRONMENT_NAME }}.tfvars