# map Terraform outputs to variables so they can be consumed by dependent jobs
parameters:
- name: terraformOutputEnv
  type: object
- name: useTerraform
  type: string
  
jobs:
- job: GetTFOutput
  displayName: Get Terraform Outputs
  dependsOn: Terraform
  condition: or(succeeded('Terraform'), eq(variables.IS_INFRA_CHANGE, false))
  steps:
  - download: current
    artifact: tfplan-$(ENVIRONMENT_NAME)
    displayName: Get tfplan

  - template: init.yml
    parameters:
      useTerraform: ${{ parameters.useTerraform }}

  - ${{ each output in parameters.terraformOutputEnv }}:
    - script: echo 
    - script: |
        echo $lookpValue
        output=$(terraform output -raw $lookpValue)
        echo $output
        echo "##vso[task.setvariable variable=value;isOutput=true]${output}"
      displayName: Get ${{ output.Value }}
      name: ${{ output.Key }}
      workingDirectory: terraform
      env:
        lookpValue: ${{ output.Value }}