# map Terraform outputs to variables so they can be consumed by dependent jobs
parameters:
- name: terraformOutputEnv
  type: object
- name: useTerraform
  type: string
  
jobs:
- job: GetTFOutput
  displayName: Get Terraform Outputs
  dependsOn: Terraform
  condition: or(succeeded('Terraform'), and(eq(variables.IS_INFRA_CHANGE, 'false'), eq(variables.IS_OUPUT_CHANGE, 'false')))
  steps:
  - download: current
    artifact: tfplan-$(ENVIRONMENT_NAME)
    displayName: Get tfplan

  - template: init.yml
    parameters:
      useTerraform: ${{ parameters.useTerraform }}

  - ${{ each entry in parameters.terraformOutputEnv }}:
    - script: |
        output=$(terraform output -json ${{ entry.Value }} | jq -er '.')
        echo "##vso[task.setvariable variable=value;isOutput=true]${output}"
      displayName: Get ${{ entry.Value }}
      name: ${{ entry.Key }}
      workingDirectory: terraform