parameters:
- name: env
  type: object
  default: ''
- name: useTerraform
  type: string
  
jobs:
- job: Terraform
  steps:
  - checkout: self
    persistCredentials: true

  - template: init.yml
    parameters:
      useTerraform: ${{ parameters.useTerraform }}

  - script: |
      terraform fmt -recursive -diff -check
      if [ $? -ne 0 ]
      then
        echo "##vso[task.logissue type=error]Format check failed. Run 'terraform fmt' locally to resolve."
        exit 1
      fi
    displayName: Check Format
    condition: in(variables.ENVIRONMENT_NAME, 'DEV', 'QA')

  - task: TerraformTaskV1@0
    displayName: Plan
    name: TerraformPlan
    ${{ if ne(parameters.env, '') }}:
      env: ${{ parameters.env }}
    inputs:
      provider: $(TF_PROVIDER)
      command: plan
      workingDirectory: $(TF_PATH)
      commandOptions: -out=$(Build.StagingDirectory)/tfplan -var-file=$(TF_VAR_FILE)
      environmentServiceNameAWS: $(TF_SERVICE_CONNECTOR)

  # Allow Terraform Apply to be skipped if there are no changes
  - script: |
      isResourceChange=$(jq -er '.resource_changes | try map(.change.actions) catch [] | flatten | map(select(. != "no-op")) | length | . > 0' $tfjson)
      isOutputChange=$(jq -er '.output_changes | try map(.["actions"]) catch [] | flatten | map(select(. != "no-op")) | length | . > 0' $tfjson)
      echo "##vso[task.setvariable variable=isResourceChange;isOutput=true]${isResourceChange}"
      echo "##vso[task.setvariable variable=isOutputChange;isOutput=true]${isOutputChange}"
    name: TerraformCondition
    displayName: Requires Change?
    env:
      tfjson: $(TerraformPlan.jsonPlanFilePath)

  - script: mv $(TerraformPlan.jsonPlanFilePath) $(Build.StagingDirectory)/tfplan.json
    name: StageTFPlanJson
    displayName: Get tfplan.json

  - publish: $(Build.StagingDirectory)
    artifact: tfplan-$(ENVIRONMENT_NAME)
    displayName: Publish Plan