parameters:
- name: directory
  type: string

steps:  
- checkout: self
  submodules: true
  
- task: npmAuthenticate@0
  inputs:
    workingFile: 'lambdas/${{ parameters.directory }}/.npmrc'

- task: Docker@2
  inputs:
    command: build
    buildContext: 'lambdas/${{ parameters.directory }}'
    Dockerfile: 'dockerfiles/lambda/nodejs/Dockerfile'
    repository: ${{ parameters.directory }}
    tags: latest
    arguments: '--secret id=npmrc-package,src=lambdas/${{ parameters.directory }}/.npmrc'
  env:
    DOCKER_BUILDKIT: 1

- task: ECRPushImage@1
  inputs:
    awsCredentials: $(AWS_SERVICE_CONNECTOR)
    regionName: $(AWS_REGION)
    imageSource: 'imagename'
    sourceImageName: ${{ parameters.directory }}
    repositoryName: ${{ parameters.directory }}
    autoCreateRepository: true
    forceDockerNamingConventions: true
    outputVariable: 'image_output'