parameters:
- name: directory
  type: string

steps:
- task: Npm@1
  displayName: Install ${{ parameters.directory }}
  inputs:
    command: install
    workingDir: ${{ parameters.directory }}

- script: zip -r "${stagingDir}/${lambdaName}.zip" .
  displayName: Zip ${{ parameters.directory }}
  workingDirectory: ${{ parameters.directory }}
  env:
    lambdaName: ${{ replace(sourceDirectory.path, '/', '_') }} 
    stagingDir: $(Build.ArtifactStagingDirectory)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: ${{ parameters.directory }}
  displayName: Publish ${{ parameters.directory }}