parameters:
- name: directory
  type: string

steps:  
- checkout: self
  submodules: true
  
- task: npmAuthenticate@0
  inputs:
    workingFile: '${{ parameters.directory }}/.npmrc'

- task: Docker@2
  inputs:
    command: build
    buildContext: '${{ parameters.directory }}'
    Dockerfile: 'dockerfiles/lambda/nodejs/Dockerfile'
    repository: ${{ lower(parameters.directory) }}
    tags: latest
    arguments: '--secret id=npmrc-package,src=${{ parameters.directory }}/.npmrc'
  env:
    DOCKER_BUILDKIT: 1

- task: ECRPushImage@1
  inputs:
    awsCredentials: $(AWS_SERVICE_CONNECTOR)
    regionName: $(AWS_REGION)
    imageSource: 'imagename'
    sourceImageName: ${{ lower(parameters.directory) }}
    repositoryName: ${{ lower(parameters.directory) }}
    autoCreateRepository: true
    forceDockerNamingConventions: true
    outputVariable: 'image_output'