parameters:
- name: lambdas
  type: object
- name: lambdasPath
  type: string

steps:
- ${{ each lambdaName in parameters.lambdas }}:
  - task: Cache@2
    displayName: Cache ${{ lambdaName }} Prod Dependencies
    inputs:
      key: npm | prod | "$(Agent.OS)" | lambdas/${{ lambdaName }}/package.json
      path: ${{ parameters.lambdasPath }}/${{ lambdaName }}/node_modules
      cacheHitVar: CACHE_RESTORED
      restoreKeys: |
        npm | $(Agent.OS)
        npm

  - script: npm install --only=prod
    displayName: Install ${{ lambdaName }} Production Dependencies
    condition: ne(variables.CACHE_RESTORED, 'true')
    workingDirectory: ${{ parameters.lambdasPath }}/${{ lambdaName }}