steps:
- task: Cache@2
  displayName: Cache Prod Dependencies
  inputs:
    key: npm | prod | "$(Agent.OS)" | lambdas/**/package.json
    path: lambdas
    cacheHitVar: CACHE_RESTORED
    restoreKeys: npm | prod | $(Agent.OS)

- script: |
    for dir in ./*
      do (cd "$dir" && npm install --only=prod)
    done
  displayName: Install Production Dependencies
  condition: ne(variables.CACHE_RESTORED, 'true')
  workingDirectory: lambdas

# - task: ArchiveFiles@2
#   displayName: Zip ${{ lambdaName }} Lambda
#   inputs:
#     rootFolderOrFile: lambdas/${{ lambdaName }}
#     includeRootFolder: false
#     archiveType: zip
#     archiveFile: $(Build.ArtifactStagingDirectory)/${{ lambdaName }}.zip
#     replaceExistingArchive: true

# - publish: $(Build.ArtifactStagingDirectory)/${{ lambdaName }}.zip
#   artifact: ${{ lambdaName }}
#   displayName: Publish ${{ lambdaName }} Artifact