steps:
- task: Cache@2
  displayName: Cache Prod Dependencies
  inputs:
    key: npm | prod | "$(Agent.OS)" | lambdas/**/package.json
    path: lambdas
    cacheHitVar: CACHE_RESTORED
    restoreKeys: npm | prod | $(Agent.OS)

- script: |
    for dir in *
      do (cd "$dir" && npm install --only=prod && zip -r "${stagingDir}/${dir}.zip" .)
    done
  displayName: Install Production Dependencies
  condition: ne(variables.CACHE_RESTORED, 'true')
  workingDirectory: lambdas
  env: 
    stagingDir: $(Build.ArtifactStagingDirectory)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: lambdas
  displayName: Publish Lambda Artifacts