parameters:
- name: buildDirectories
  type: object
  default: ''

steps:
${{ if eq(parameters.buildDirectories, '')}}:
  - script: echo "##vso[task.logissue type=warning]Warning no buildDirectories specified."

- script: |
    for dir in *
      do (cd "$dir" && npm install --only=prod && zip -r "${stagingDir}/${dir}.zip" .)
    done
  displayName: Install Production Dependencies
  workingDirectory: lambdas
  env: 
    stagingDir: $(Build.ArtifactStagingDirectory)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: lambdas
  displayName: Publish Lambda Artifacts