parameters:
- name: buildContainerImage
  type: string
  default: ''
- name: buildLambdas
  type: object

jobs:
- job: GetContainerImage
  displayName: Get Container Image
  steps:
  - template: ../helpers/container-get-image.yml
    parameters:
      buildContainerImage: ${{ parameters.buildContainerImage }}

- job: ValidateLambdas
  displayName: Validate Lambdas
  dependsOn: GetContainerImage
  variables:
    CONTAINER_IMAGE: $[ dependencies.GetContainerImage.outputs['GetImage.url'] ]
  container: 
    image: $(CONTAINER_IMAGE)
    env:
      CI: true
  steps:
  - ${{ each lambdaName in parameters.buildLambdas }}:
    - task: Cache@2
      displayName: Check ${{ lambdaName }} Dependency Cache
      inputs:
        key: npm | "$(Agent.OS)" | package-lock.json
        path: lambdas/${{ lambdaName }}/node_modules
        cacheHitVar: CACHE_RESTORED
        restoreKeys: |
          npm | $(Agent.OS)
          npm

    - script: npm install --only=prod
      displayName: Install ${{ lambdaName }} Dependencies
      condition: ne(variables.CACHE_RESTORED, 'true')
      workingDirectory: lambdas/${{ lambdaName }}

    - script: npm test
      displayName: Unit Test ${{ lambdaName }}
      condition: or(eq(variables.ENVIRONMENT_NAME, 'DEV'), eq(variables.ENVIRONMENT_NAME, 'QA'))
      workingDirectory: lambdas/${{ lambdaName }}

    - publish: $(System.DefaultWorkingDirectory)/lambdas/${{ lambdaName }}
      displayName: Publish ${{ lambdaName }} Artifact
      artifact: ${{ lambdaName }}
