parameters:
- name: useTerraform
  type: string
  default: true

jobs:
- deployment: Terraform
  environment: $(ENVIRONMENT_NAME)
  strategy:
    runOnce:
      deploy:  
        steps:
        - checkout: self
              
        - download: current
          artifact: tfplan-$(ENVIRONMENT_NAME)
          displayName: Get tfplan

        - template: ../Terraform/init.yml
          parameters:
            useTerraform: ${{ parameters.useTerraform }}

        - task: TerraformTaskV1@0
          displayName: Apply Terraform
          name: TerraformApply
          env:
            AZDO_PERSONAL_ACCESS_TOKEN: '$(AZDO_PERSONAL_ACCESS_TOKEN)'
          inputs:
            provider: $(TF_PROVIDER)
            command: apply
            workingDirectory: $(TF_PATH)
            commandOptions: $(Pipeline.Workspace)/tfplan-$(ENVIRONMENT_NAME)/tfplan
            environmentServiceNameAWS: $(TF_SERVICE_CONNECTOR)